apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc
  namespace: file-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
